services:
  frontend:
    image: localhost:5000/frontend-secure:v1
    ports:
      - "8080:80"
    read_only: true
    security_opt:
      - no-new-privileges:true
    depends_on:
      - backend

  backend:
    image: localhost:5000/backend-secure:v1
    ports:
      - "5001:5000"
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    secrets:
      - vault_role_id
      - vault_secret_id
    depends_on:
      db:
        condition: service_healthy
      vault:
        condition: service_started

  db:
    image: mariadb:10.6
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_root_password
      - MARIADB_DATABASE=netops
    secrets:
      - mariadb_root_password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 12

  vault:
    image: hashicorp/vault:1.19
    ports:
      - "127.0.0.1:8200:8200"
    command: server -config=/vault/config/vault.hcl
    volumes:
      - vaultdata:/vault/file
      - ./vault/config:/vault/config:ro
    cap_add:
      - IPC_LOCK

secrets:
  mariadb_root_password:
    file: ./.secrets/mariadb_root_password
  vault_role_id:
    file: ./.secrets/vault_role_id
  vault_secret_id:
    file: ./.secrets/vault_secret_id

volumes:
  dbdata:
  vaultdata:
